export const enum PrepsFileModelType {
  CURRENCY_LIST = 'CURRENCY_LIST',

  PREPAYMENT_DATA = 'PREPAYMENT_DATA',

  PREPAYMENT_ENTRY = 'PREPAYMENT_ENTRY',

  AMORTIZATION_ENTRY = 'AMORTIZATION_ENTRY',
}
