export const enum PrepsFileDeleteProcessType {
  DELETE_PREPAYMENT_DATA = 'DELETE_PREPAYMENT_DATA',

  DELETE_PREPAYMENT_ENTRY = 'DELETE_PREPAYMENT_ENTRY',

  DELETE_AMORTIZATION_ENTRY = 'DELETE_AMORTIZATION_ENTRY',
}
